const indianStates = [
    { id: 1, value: 'andaman-nicobar', label: 'Andaman and Nicobar Islands' },
    { id: 2, value: 'andhra-pradesh', label: 'Andhra Pradesh' },
    { id: 3, value: 'arunachal-pradesh', label: 'Arunachal Pradesh' },
    { id: 4, value: 'assam', label: 'Assam' },
    { id: 5, value: 'bihar', label: 'Bihar' },
    { id: 6, value: 'chandigarh', label: 'Chandigarh' },
    { id: 7, value: 'chhattisgarh', label: 'Chhattisgarh' },
    { id: 8, value: 'dadar-nagar-haveli', label: 'Dadar and Nagar Haveli' },
    { id: 9, value: 'daman-diu', label: 'Daman and Diu' },
    { id: 10, value: 'delhi', label: 'Delhi' },
    { id: 11, value: 'goa', label: 'Goa' },
    { id: 12, value: 'gujarat', label: 'Gujarat' },
    { id: 13, value: 'haryana', label: 'Haryana' },
    { id: 14, value: 'himachal-pradesh', label: 'Himachal Pradesh' },
    { id: 15, value: 'jammu-kashmir', label: 'Jammu and Kashmir' },
    { id: 16, value: 'jharkhand', label: 'Jharkhand' },
    { id: 17, value: 'karnataka', label: 'Karnataka' },
    { id: 18, value: 'kerala', label: 'Kerala' },
    { id: 19, value: 'lakshadweep', label: 'Lakshadweep' },
    { id: 20, value: 'madhya-pradesh', label: 'Madhya Pradesh' },
    { id: 21, value: 'maharashtra', label: 'Maharashtra' },
    { id: 22, value: 'manipur', label: 'Manipur' },
    { id: 23, value: 'meghalaya', label: 'Meghalaya' },
    { id: 24, value: 'mizoram', label: 'Mizoram' },
    { id: 25, value: 'nagaland', label: 'Nagaland' },
    { id: 26, value: 'odisha', label: 'Odisha' },
    { id: 27, value: 'puducherry', label: 'Puducherry' },
    { id: 28, value: 'punjab', label: 'Punjab' },
    { id: 29, value: 'rajasthan', label: 'Rajasthan' },
    { id: 30, value: 'sikkim', label: 'Sikkim' },
    { id: 31, value: 'tamil-nadu', label: 'Tamil Nadu' },
    { id: 32, value: 'telangana', label: 'Telangana' },
    { id: 33, value: 'tripura', label: 'Tripura' },
    { id: 34, value: 'uttar-pradesh', label: 'Uttar Pradesh' },
    { id: 35, value: 'uttarakhand', label: 'Uttarakhand' },
    { id: 36, value: 'west-bengal', label: 'West Bengal' },
];
  
export default indianStates;
  